price = float(input("Введите цену закупки телефона: "))
sell_price = float(price + price * 0.3 )
price5 = float(price - price * 0.05)
price10 = float(price - price * 0.1)
price15 = float(price - price * 0.15)
print("Цена продажи:", sell_price)
print("Цена продажи со скидкой 5%:", price5)
print("Цена продажи со скидкой 10%:", price10)
print("Цена продажи со скидкой 15%:", price15)