text = input('Введите цифры через пробел: ')
num = text.split()
numbers = list(map(int, num))
sum_result = sum(numbers)
max_result = max(numbers)
avr = sum_result / len(numbers)
print('Общая сумма:', sum_result)
print('Максимальная цифра:', max_result)
print('Среднее арифметическое:', avr)